#######################
# Aurea Central Jervis Example
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-central-jervis-example
# This project is based on https://github.com/aurea-central-jervis-example/aurea-central-jervis

language: java

before_install:
  - sudo apt update
  - sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends vim
  - echo test again
  - mkdir -p build
  - touch build/teste.log

install:
  - echo "this is installation part"
  - echo "this is another installation print"

env:
 - Test1="test"

before_script:
  - echo "this is before script section"
  - echo "it will contain steps executed before the script section starts"

stability: None

branches:
  only:
    - master
    - release
    - develop
    - feature

cache:
  directories:
    - ${HOME}/.m2
    - ${HOME}/.gradle
    - ${HOME}/.sdkman


